biocore/biom-format

ChangeLog.md
biom/util.py
tests/test_util.py

If the user tried to load an HDF5 file but H5PY was not available in the 
installation, a misleading error message would come up, this has been fixed
and an extra test case has been added.
Fixes #584

BUG: Remove misleading error message

---

biom/commands/table_summarizer.py

Fixes #598. Pipe worked previously on OSX, but did not work on Linux. I've manually verified this on RHEL. The following did not work previously, but now works with this change:
```bash
biom summarize-table -i foo.biom | more
```

ENH: allow pipe for table summarizer

---

ChangeLog.md
biom/util.py
tests/test_util.py

Add an explicit check to verify the passed file is not empty.
Fixes #614

BUG/ENH: Check for filesize when reading file

---

ChangeLog.md
biom/table.py
tests/test_table.py

Fixes #608 
This change allows for custom parsers and formatters. I don't think that it is sustainable adding in more hardcoded parsing types. Within picrust, we'll be able to just define a parser/formatter that serializes the nested lists in a few of the metadata types into json.

ENH/TST: custom parsers and formatters for hdf5 metadata

---

scripts/biomcli

Adds the head command. This really just wraps `Table.head` so I didn't think there was a need to add in additional tests.

Added head

---

biom/cli/__init__.py
biom/cli/table_converter.py
biom/cli/util.py
scripts/biom
tests/test_cli/test_table_converter.py

biom convert finalization

---

setup.py

biom_format is using string_type from the future module, but this is included in version 0.15.0.
https://github.com/PythonCharmers/python-future/commit/3b9c2115aa38b516c82ff6bf370eeac31b9b6a62

Update `future` dependency

---

ChangeLog.md
biom/table.py
tests/test_table.py

@josenavas, possible for a review on this? Asking as I believe you wrote the normal subset method. Basically, the subset kills you when handling metadata, which is fine for one-off runs, but I need to do repeated subsetting for EMP in the context of the block decomposition for unifrac. See [here](https://gist.github.com/wasade/60db4059e3b7e42bb648db1d10ef72d6) for the motivator, which I'd like to get running tomorrow on EMP oref. This PR doesn't block, but it's necessary for this approach to be feasible

Rapid subset

---

setup.py

Cython does not automagically add a `-I<pathtonumpyincludes>` option to the compiler directives. Compiling the modules therefore only worked if there was a numpy version installed to system/default directories. If multiple versions where installed, compilation always used the headers from the system/default installation.

add correct numpy c include path (fixes #705)

---

biom/cli/__init__.py

Allows `biom -h`, `biom head -h`, etc.

Adds context_settings to click.group

---

ChangeLog.md
biom/table.py
tests/test_table.py

Tables w/o metadata weren't concatenating correctly.

BUG/TST: concat was not handling missing metadata properly

---

biom/cli/__init__.py

Another small one. `BrokenPipeErrors` can happen when piping from a python process to something else, eg `biom table-ids -i foo | head`. This is inelegant, but the issue is rather low level in Python itself.

ENH: work around possible broken pipe errors

---

biom/cli/table_validator.py
tests/test_cli/test_validate_table.py

This had the consequence of flagging tables as invalid when nnz values were
stored as np.int32 or np.int16 (somehow this happened for a Qiita table).
The format document specifies that this value should be int, but it doesn't specify
the specific representation, so I assume all subdtypes of np.integer should be safe.

BUG: All ints should be accepted

---

MANIFEST.in

@unode, able to do a quick review? I see the following files now following a `python setup.py sdist`
```bash
$ ls biom-format-2.1.6.dev0/tests/test_data/
total 176
-rw-r--r--  1 mcdonadt  staff     0B Apr 28  2017 __init__.py
-rw-r--r--  1 mcdonadt  staff    63B Apr 28  2017 bad_table.txt
-rw-r--r--  1 mcdonadt  staff    97B Apr 28  2017 bad_table.txt.gz
-rw-r--r--  1 mcdonadt  staff    21K Apr 28  2017 empty.biom
-rw-r--r--  1 mcdonadt  staff     0B Apr 28  2017 no-contents.biom
-rw-r--r--  1 mcdonadt  staff    46K Apr 28  2017 test.biom
-rw-r--r--  1 mcdonadt  staff   2.3K Apr 28  2017 test.json
-rw-r--r--  1 mcdonadt  staff   678B Apr 28  2017 test.json.gz
```

Fixes #765

---

.travis.yml
ChangeLog.md
biom/cli/table_validator.py
biom/parse.py
biom/table.py
biom/util.py
setup.py
tests/test_table.py

Some additional error checking when writing out to HDF5, with some additional care on the general formatter. 
The metadata are still quite awkward, and this further underscores the need to transition the metadata representation to `pandas`.

Some additional error checking on to_hdf5

---

doc/index.rst

...and outdated biom install documentation for R was removed users reported the `biom` package in CRAN no longer exists.

R bioconductor link updated

---

ChangeLog.md
biom/table.py
biom/tests/test_table.py

So this is a proposed fix to #808. It basically specifies the fill value for sparse data explicitly. I also added a test to check for that in the future. 
Before that the the matrix data was first converted to individual `pandas.SparseSeries` and passed to `pandas.SparseDataFrame`. This is now done directly without the intermediate allocations since `SparseDataFrame` accepts any scipy sparse matrix. If `Table.matrix_data` can be something else than a numpy matrix or scipy sparse matrix this might not work but for now all tests seem to pass. Happy to change that back to the old behavior if that was on purpose.
As a side effect `to_dataframe` is now much faster on large sparse data sets. Takes about 20s on my machine for the American Gut biom (was more than 30m before).

make `Table.to_dataframe` create real sparse frames

---

biom/parse.py
biom/table.py

Addresses #776 
Renamed `fp` to `file_obj` to reduce confusion over acceptable parameter types.
Updated annotation for `file_obj` to clarify acceptable types.

clarified docstring for parse_biom_table, addresses #776

---

biom/table.py

- in tsv data with row and column names the first cell of the   header is usually left empty, e.g. tsv export from R does it   like this
- the content of the 1st cell in the header seems not to appear   in the header anyway, so leaving it unstripped might also be fine
- stripping the leading tab leads to an error:
```
Traceback (most recent call last):
File "/gpfs1/data/galaxy_server/galaxy/database/dependencies/_conda/envs/__biom-format@2.1.5/bin/biom", line 6, in <module>
sys.exit(biom.cli.cli())
File "/gpfs1/data/galaxy_server/galaxy/database/dependencies/_conda/envs/__biom-format@2.1.5/lib/python3.6/site-packages/click/core.py", line 722, in __call__
return self.main(*args, **kwargs)
File "/gpfs1/data/galaxy_server/galaxy/database/dependencies/_conda/envs/__biom-format@2.1.5/lib/python …
```

don't strip tabs from header

---

ChangeLog.md
biom/cli/__init__.py
biom/cli/metadata_exporter.py

This pull request addresses https://github.com/biocore/biom-format/issues/820 by wrapping `Table.metadata_to_dataframe()` in a CLI method `biom export-metadata`.
Example usage:
```
biom add-metadata -i ./biom-format/examples/min_sparse_otu_table_hdf5.biom -o ./test.biom --observation-metadata-fp ./biom-format/examples/obs_md.txt --sample-metadata-fp ./biom-format/examples/sam_md.txt
biom export-metadata -i ./test.biom --sample-metadata-fp ./metadata_sample.tsv --observation-metadata-fp ./metadata_observation.tsv
```

Export metadata as TSV

---

ChangeLog.md
pyproject.toml
setup.py

`biom-format` now requires that `numpy` and `cython` should be present in the build environment prior the builing.
By implementing the PEP518, 
https://github.com/biocore/biom-format/blob/fd84172794d14a741a5764234d7a28416b9dba08/setup.py#L18-L21 and https://github.com/biocore/biom-format/blob/fd84172794d14a741a5764234d7a28416b9dba08/setup.py#L24-L27 are not longer required.
Also, this PR resolves the issue of having `biom-format` in `install_requires` installed before `cython`, which leads to a failure
```python
Complete output (12 lines):
Traceback (most recent call last):
File "/tmp/pip-install-hani473s/biom-format/setup.py", line 25, in <module>
from Cython.Build import cythonize
ModuleNotFoundError: No module named 'Cython'
During handling of the above exception, another exception …
```

Numpy and Cython as build dependencies, PEP518

---

ChangeLog.md
biom/table.py
biom/tests/test_table.py
biom/util.py

Added a (much) faster way to merge tables when the axes overlap. `Table.concat` is still (much) faster for the special case where one axis is assured to be disjoint. This revised merge method can operate on many tables at once, unlike the existing `merge` which took a single table. 
I don't have exact timing information, but the existing merge with four tables, each with roughly 600 samples and 1M features, was around 3 hours. This new method took a few minutes.

Fast merge

---

ChangeLog.md
biom/table.py

This is a revamp of #771 without adding external dependencies.

fix #770 date keyword in Python >= 3.7

---

.github/workflows/python-package-conda.yml
ChangeLog.md
biom/table.py
biom/tests/test_table.py

This pull request adds alignment functionality, to allow the biom table to be aligned against metadata (represented as `pd.DataFrame`) and trees (represented as `skbio.TreeNode`).
I have made this a little more general, allowing these alignment methods to be performed on both axes (sample and observations). 
Once we have agreed on the basic user interface, I will push in the remaining unittests.
Outstanding questions
1. Should we enable an inplace option?  Maybe useful for massive datasets.
2. Should we enable a `how` or `join` flag, specifying if this is going to be an inner, outer, left or right join?  Right now, I'm only implementing an inner flag since those are my only use cases.  But if there is a compelling use case, I am open for discussion.

Align methods for #858

---

biom/table.py
biom/util.py

For collapses requiring high volumes of partitions, these changes empirically offered about a 10x reduction in runtime. In particular, this greatly improves performance for `redbiom.fetch` when merging samples.

Improve Table.collapse by roughly 10x

---

biom/_filter.pyx
biom/table.py
biom/tests/test_table.py
pytest.ini

Improve handling of IDs. 
* set a fixed width on load from HDF5
* set a fixed with on update of IDs
* avoid forcing `dtype=object` on construction
These are done for the benefit of lower level optimizations where specificity of the dtype is high value.

Preserve str type, set fixed width on load, and set fixed with on update_ids

---

.github/workflows/python-package-conda.yml
README.md
biom/table.py

I'm not sure if non-string IDs were ever officially supported for BIOM tables, but some of the Empress test code ([these lines, in particular](https://github.com/biocore/empress/blob/bf6f755c5187e543ff13c2c624b153fb97918b23/tests/python/test_tools.py#L143-L145)) involved setting IDs to integers. It looks like [this commit](https://github.com/biocore/biom-format/commit/3876827597658d4a05192958c715ef4738c30ef5) broke this behavior, and by extension this particular Empress test -- it triggered the following error:
```
ERROR: test_match_inputs_no_tips_in_table (python.test_tools.TestTools)
----------------------------------------------------------------------
Traceback (most recent call last):
File "/home/runner/work/empress/empress/tests/python/test_tools.py", line 143, in …
```

Clarification about ID type in the docs for Table.update_ids

---

.github/workflows/python-package-conda.yml
ChangeLog.md
biom/table.py

Avoid dense representation on one_to_many. This code path was implicated in `woltka collapse`. 
Note this is a WIP, I am asserting the memory reduction in `woltka collapse` right now. However, the high memory requirement is nearly certainly due to the dense memory representation previously used. 
cc @antgonza @qiyunzhu

PERF: use sparse matrix for table.collapse(..., one_to_many=True)

---

biom/table.py

When converting observation metadata to dataframe the column names were taken from the first row. When the first row had missing values (i.e. incomplete taxonomic assignment) then the number of columns would not match the column headers. I changed it to take the maximal list of column names from all rows.

take column names from all metadata not just first entry

---

index.html

The old URLs redirect to the new URLS. Note also now HTTPS.

Update URL for MG-RAST, VAMPS project

---

biom/cli/table_summarizer.py

``locale.format`` was deprecated in Python 3.7, see https://docs.python.org/3/library/locale.html#locale.format
Closes #908

locale.format --> locale.format_string

---

biom/table.py

This appears to fix #907, biom export-metadata did not preserve the metadata key order in the BIOM file.
It may have side effects though - perhaps some existing usage now assumes/expects the sorted behaviour of the ``metadata_to_dataframe`` method?

Don't sort metadata order

---

setup.py

I didn't see instructions regarding whether the PR should be merged into master or develop.
Fix #898 
Remove Cython from the package requirements since it's only needed at installation time and already listed in `pyproject.toml` build requirements.
I didn't make any other changes here but I did notice that the whole package installation/building configuration uses outdated mechanisms. You may consider making further changes:
* Setuptools now [fully supports pyproject.toml](https://setuptools.pypa.io/en/latest/userguide/pyproject_config.html). This would let you get rid of `setup.cfg` and `pytest.ini` as well.
* Supporting `python setup.py test` is not typically done anymore.
* You can pre-compile your `.pyx` modules into `.c` ones and make those part of your source distribution instead. …

chore: remove cython from requirements

---

ChangeLog.md
biom/_subsample.pyx
biom/table.py
biom/tests/test_table.py
doc/index.rst

Fixes #914. You can now specify the random seed on call to `Table.subsample(...)`.
cc @gibsramen @rob-knight

Explicitly allow setting a random seed for subsample

---

biom/cli/table_head.py

Fixes #899 
@peterjc, I'm not allowing values of 0 here as obtaining sample or observation IDs can be performed with `biom table-ids`

Disallow head to have values <= 0

---

ChangeLog.md
biom/table.py

`Table._fast_merge` was performing poorly on large tables. Here we revise the algorithm used.
List based, on large data, we get:
```bash
User time (seconds): 2990.23
Elapsed (wall clock) time (h:mm:ss or m:ss): 51:55.52
Maximum resident set size (kbytes): 52802340
```

Faster merge

---

ChangeLog.md
biom/_subsample.pyx

The input data is supposed to be integer, but it is represented using fp64.
If the elements are not precisely integer, the previous logic would fail, possibly leading to data corruption.
The new version enforces the integer constraint.

More gracefully deal with not-perfectly-integer inputs

---

ci/aarch64.conda_requirements.txt
ci/conda_requirements.txt

The package `natsort` is listed as a dependency but it is actually never used. Instead, BIOM has a built-in `natsort` function. Therefore this dependency can be removed. See:
https://github.com/scikit-bio/scikit-bio/issues/2007

Removed dependency on natsort

---

ChangeLog.md
biom/table.py
biom/util.py

Addresses #984 
The average import time (`python -X importtime -c 'import biom'`) over 7 runs for the current master branch of BIOM is 0.44s. Moving the imports of the required dependencies into their respective functions brings the average import time down to 0.19s, a **2.3x** speedup.
Performance of individual functions is only impacted on the first call. For example, the first call to `Table.to_dataframe()` is 247 microseconds, while all subsequent calls are 180 microseconds. This is due to the module being cached in `sys.modules` after the first call. The execution time of `to_dataframe()` without the import statement inside the function is 180 microseconds.

Speedup import time with lazy imports
