biom/table.py
tests/test_table.py

Fixes #585 
Sorry for the delay on this. It turns out it was a pretty easy fix, I just needed to find the time to check where was the issue originated.

Normalizing the representation of missig/null metadata

---

biom/__init__.py
biom/interfaces/html/config/convert.py
biom/interfaces/html/config/normalize_table.py
biom/interfaces/html/config/show_install_info.py
biom/interfaces/html/config/summarize_table.py
biom/interfaces/html/config/validate_table.py
biom/interfaces/html/input_handler.py
biom/interfaces/optparse/config/convert.py
biom/interfaces/optparse/config/summarize_table.py
biom/interfaces/optparse/input_handler.py
biom/interfaces/optparse/output_handler.py
biom/parse.py
biom/table.py
biom/util.py
tests/test_parse.py

This is blocking other pending PRs. Should resolve outstanding pep8 issues.

Pep8 updates

---

tests/test_table.py

ENH: Replace mktemp with NamedTemporaryFile

---

biom/table.py

This just shifts these methods from being defined within `Table.to_hdf5` and `Table.from_hdf5` out to the module namespace. There is no benefit in having them within the methods, and it just complicates those methods substantially. Additionally, there is a specific need within PICRUSt to be able to import the vlen formatter.

MAINT: moved nested functions to module namespace

---

ChangeLog.md
biom/table.py
tests/test_table.py

BUG/DOC/TST: fixes #625

---

ChangeLog.md

One step closer to 2.1.4. We need to deploy and test against QIIME before the release is actually cut, marking as 2.1.4rc1 for now.
NOTE: version tags across the codebase have _not_ been updated. Will do that on release.

DOC: listing 2.1.4 changes

---

doc/index.rst

@gregcaporaso and I worked on this. Fixes #649.

DOC: modernize index page

---

biom/cli/table_summarizer.py
scripts/biomcli
tests/test_cli/test_summarize_table.py

Also checks that output path is writable

REF: shuffled API boundary for table loading

---

biom/parse.py
tests/test_parse.py

This code is adapted from [gregcaporaso/scaling-octo-robot](https://github.com/gregcaporaso/scaling-octo-robot), which @jairideout and I pair-programmed.

adds API for creating a Table from a uc file

---

biom/cli/__init__.py
biom/cli/table_validator.py
scripts/biomcli
tests/test_cli/test_validate_table.py

This is the best I could manage without rewriting a lot of code.
Basically just a crude wrapper around what used to be a `Command` class.

REF: validate-table uses click

---

doc/index.rst

Support for BIOM-Format v1.0.0 was added into usearch v8.1.1803.

Added mention of usearch

---

ChangeLog.md
biom/cli/uc_processor.py

This slipped through in the 2.1.5 release.

BUG: fixes #683

---

doc/index.rst

PhyloToAST makes extensive use of BIOM-format files in the analysis and visualization of microbiome data

DOC: adds PhyloToAST to software list

---

doc/index.rst

project github url: https://github.com/SMRUCC/GCModeller
home: http://gcmodeller.org
GCModeller metagenome analysis tool component with native supports of BIOM v1.0 json format.

Submit new project that using BIOM

---

setup.py

Update future package requirement to 0.16.0 to avoid error

---

doc/index.rst

I had linked to  the bitbucket project earlier today but I deleted that PR and am submitting a new one w/ the link to the most canonical website for the project.

Add MetaPhlAn 2 as a project using the BIOM format

---

ChangeLog.md
biom/cli/table_validator.py
biom/table.py
doc/documentation/adding_metadata.rst
doc/documentation/biom_conversion.rst
doc/documentation/biom_format.rst
doc/documentation/format_versions/biom-2.0.rst
doc/documentation/format_versions/biom-2.1.rst
tests/test_table.py
tests/test_util.py

Some issues

---

.travis.yml
ChangeLog.md
biom/cli/table_validator.py
biom/table.py
setup.py
tests/test_table.py
tests/test_util.py

Closing out a few more issues for the milestone, including pandas support.

More 2.1.6 milestone issues

---

biom/table.py

@ElDeveloper, able for quick review? Just moving the notes sections

DOC: moving notes sections

---

ChangeLog.md
biom/cli/table_ids.py

A quick one. We do not currently exercise the CLI directly in other places, and this is a really minimal wrapper, so I'm hoping this is just acceptable as is.

IDs via the CLI

---

biom/table.py

Added documentation to the table class in table.py

---

doc/documentation/format_versions/biom-1.0.rst

fixes #779

---

ChangeLog.md
biom/parse.py

Order is now maintained in JSON parsing.

Fixes #781

---

ChangeLog.md
biom/table.py
tests/test_table.py

Align a table to another table.

Table alignment

---

ChangeLog.md
biom/table.py

10s of milliseconds vs. minutes (...before I killed the process out of boredom).

Massive performance boost to Table.collapse

---

ChangeLog.md

DOC: Add hyperlink to issue

---

.travis.yml
ChangeLog.md
biom/cli/table_validator.py
biom/parse.py
biom/table.py
biom/tests/test_cli/test_validate_table.py
biom/tests/test_parse.py
biom/tests/test_table.py

* Fixes #378
* Removes Python 2.7 support

WIP: Low hanging items

---

ChangeLog.md
biom/table.py
biom/tests/test_table.py

Fixes #827 
@antgonza, would it be possible for a review?

Metadata edgecase

---

.travis.yml
ChangeLog.md

Testing whether travis builds support py38

BLD: test support for py38

---

.travis.yml
ChangeLog.md
setup.py

BLD/DOC: bump scipy version and make changelog mention

---

.travis.yml

We need to update sphinx version support but that is a different issue for another day.

DOC: move sphinx to py37 as it seems pesky on py36

---

biom/table.py

Shave about 10% time (if compressed=False is used)

perf: cache nnz on write

---

biom/table.py
biom/tests/test_table.py

Metadata slashes

---

biom/table.py
biom/tests/test_parse.py

Empty tsv edgecase

---

biom/tests/test_table.py
doc/conf.py

relax test to allow h5py to vary, cc @tillea

---

biom/cli/table_validator.py

Silent failures are incredibly frustrating to debug.
(None of these was actually why my file was failing, separate issue to follow)

Report all validation failures

---

index.html

Using GitHub link, see also
* Documentation on Read The Docs: https://thapbi-pict.readthedocs.io/
* Software released on PyPI: https://pypi.org/project/thapbi-pict/
* Zenodo DOI for software: https://doi.org/10.5281/zenodo.4529395
Version 0.14.1 released today includes optional BIOM output for the sequence-versus-sample results.

Link to THAPBI PICT under projects using the BIOM format

---

ChangeLog.md

Issues reflected listed in the diff, this should not be merged until after the associated PRs are merged.

DOC: revise changelog to reflect recent PRs

---

doc/index.rst

Added on the list "mia (TreeSummarizedExperiment; R/Bioconductor)" and the link pointing to(http://microbiome.github.io/)

Addition of a project using the BIOM format

---

biom/table.py

MAINT: support capital T Taxonomy on adding metadata
